### ISSUE TITLE
Input beam not returned correctly for kickers maps (`track_madx_kicker`)

### ISSUE THREAD

**Issue by EustacheG** [ULB-Metronu/georges#39]
In manzoni/maps/madx_thick.py, the input beam (b1) given at the end by the kickers map (track_madx_kicker) seems to be wrong. The xp and yp coordinates are correctly modified according to the kick parameter, but then it is this modified b1 which is rendered at the end. The two following screenshots (kicker_map for the code and kicker_notebook_example for an example) illustrate the situation.

<img width="731" alt="kicker_map" src="https://user-images.githubusercontent.com/32551680/82058669-58289600-96c5-11ea-99a5-f31c46cd3519.png">
<img width="809" alt="kicker_notebook_example" src="https://user-images.githubusercontent.com/32551680/82058675-5959c300-96c5-11ea-878d-7c906f55ac33.png">

**Comment by rtesse** [comment]
`b2` is correct: it is the exit beam from the kicker.

`b1` usually remains as the "input" beam but in this case it is the `b1` after the half drift and after the kick, which is not ideal.

One possibility : copy b1 at the begining of the function (see how marker does it ?) then proceed. Indicate with a comment in the code that this is not ideal but required in this case.

**Comment by rtesse** [comment]
Correct, commit and PR :)
