### ISSUE TITLE
Numba parallel execution warning still there for `aperture_check` functions

### ISSUE THREAD

**Issue by EustacheG** [ULB-Metronu/georges#40]
The numba warning is still there during a first track in Manzoni, for aperture_check functions (in apertures.py). The screenshot attached illustrates the warning.

<img width="1043" alt="numba_parallel_execution_warning" src="https://user-images.githubusercontent.com/32551680/82059367-3845a200-96c6-11ea-82b4-897b602ff610.png">

**Comment by rtesse** [comment]
@EustacheG La question elle est vite répondue :) Tu peux enlever le `parallel=True` et faire une PR.

**Comment by chernals** [comment]
The `parallel=true` option has been removed in the develop branch.
