### ISSUE TITLE
create new release ?

### ISSUE THREAD

**Issue by arielzn** [ULB-Metronu/georges#66]
hello,

on the installation guide here:

https://ulb-metronu.github.io/georges/installation.html

is mentioned to checkout the `tags/2023.1` which seems not to be present on this repo. 

I guess is missing to push the version tags ? As there are several commits since the latest tag present `2019.2`

getting a proper release or tag on the repo, will help to create an easybuild recipe to install the software.

**Comment by rtesse** [comment]
Hello, 

The tag has been created and a release has been done. Moreover, the package is now available on pypi and can be installed using 

` pip install georges`

Regards,

Robin.

**Comment by rtesse** [comment]
Hello,
We made a new release of georges (2024.2) which is available from Pypi. I will close this issue as it is resolved.
Regards,
Robin
